version: "3.8"

services:
  web:
    build: .
    container_name: vflask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Welcome@123
      - MYSQL_DATABASE=studentdb

  db:
    image: mysql:8.0
    container_name: mysql-vcontainer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
