apiVersion: apps/v1
kind: Deployment
metadata:
  name: vflask-app
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-container
          image: venkateshsagar/flask-mysql-app:v2
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              value: flaskdb
          resources:          # ✅ Add this section
            requests:
              cpu: "250m"     # requests = guaranteed minimum
              memory: "256Mi"
            limits:           # limits = maximum allowed
              cpu: "500m"
              memory: "512Mi"
