apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: flask-mysql-app
type: Opaque
data:
  mysql-root-password: V2VsY29tZUAxMjM=   # base64 of Welcome@123
  mysql-database: c3R1ZGVudGRi           # base64 of studentdb
